//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public int Id_barang { get; set; }
        public string nama_barang { get; set; }
        public Nullable<int> jumlah_barang { get; set; }
        public Nullable<int> harga_barang { get; set; }
    }
}
